import UserRoute from "./UserRoute.js";
import GameRoute from "./GameRoute.js";
import PostProjectRoute from "./PostProjectRoute.js";
import PlansRoute from "./PlansRoute.js";
import PlanpurchaseRoute from "./PlanpurchaseRoute.js";
import Apply from "./ApplyRoute.js";
import SubmitProjectRoute from "./SubmitProjectRoute.js";
import MessageRoute from "./MessageRoute.js";
import ChatBotRoute from "./ChatBotRoute.js";
import HelpCenterRoute from "./HelpCenterRoute.js";
import PayoutRoute from "./payoutRoutes.js";
import BlogRoute from "./BlogRoute.js";
import QuizRoute from "./QuizRoute.js";
import SiteSettingsRoute from "./SiteSettingsRoute.js";
import AutoCompletionRoute from "./AutoCompletionRoute.js";
import ActivityRoute from "./ActivityRoute.js";
import TeamHubRoute from "./TeamHubRoute.js";
import AdminAnalyticsRoute from "./AdminAnalyticsRoute.js";
import ProjectMarketplaceRoute from "./ProjectMarketplaceRoute.js";
import ProjectPurchaseRoute from "./ProjectPurchaseRoute.js";
import ReportRoute from "./ReportRoute.js";
import VIPRoute from "./VIPRoute.js";
import FreelancerMatchRoute from "./FreelancerMatchRoute.js";
import AiTamplateRoute from "./AiTamplateRoute.js";
import CallRoute from "./CallRoute.js";
import DataSetRoute from "./DataSetRoute.js";
import FworkPrimeRoute from './FworkkPrimeRoute.js'
import SkillRoute from "./SkillRoute.js";
import CertificateRoute from "./CertificateRoute.js";
import NetlifyRoute from "./NetlifyRoute.js";
import StudioRoute from "./StudioRoute.js";

const setupRoutes = (app) => {
  app.use("/api/v1/users", UserRoute);
  app.use("/api/v1/studio", StudioRoute);
  app.use("/api/v1/postproject", PostProjectRoute);
  app.use("/api/v1/plans", PlansRoute);
  app.use("/api/v1/planpurchase", PlanpurchaseRoute);
  app.use("/api/v1/apply", Apply);
  app.use("/api/v1/projectapply", Apply);
  app.use("/api/v1/submit", SubmitProjectRoute);
  app.use("/api/v1/message", MessageRoute);
  app.use("/api/v1/chat", ChatBotRoute);
  app.use("/api/v1/helpCenter", HelpCenterRoute);
  app.use("/api/v1/payout", PayoutRoute);
  app.use("/api/v1/blog", BlogRoute);
  app.use("/api/v1/quiz", QuizRoute);
  app.use("/api/site-settings", SiteSettingsRoute);
  app.use("/api/v1/auto-completion", AutoCompletionRoute);
  app.use("/api/v1/activity", ActivityRoute);
  app.use("/api/v1/teamhub", TeamHubRoute);
  app.use("/api/v1/admin-analytics", AdminAnalyticsRoute);
  app.use("/api/v1/call", CallRoute);
  app.use("/api/v1/project-marketplace", ProjectMarketplaceRoute);
  app.use("/api/v1/project-purchase", ProjectPurchaseRoute);
  app.use("/api/v1/reports", ReportRoute);
  app.use("/api/v1/aitamplate", AiTamplateRoute);
  app.use("/api/v1/vip", VIPRoute);
  app.use("/api/v1/freelancers", FreelancerMatchRoute);
  app.use("/api/v1/dataset", DataSetRoute);
  app.use("/api/v1/fworkprime", FworkPrimeRoute);
  app.use("/api/v1/skills", SkillRoute);
  app.use("/api/v1/certificate", CertificateRoute);
  app.use("/api/v1/game", GameRoute);
  app.use("/api/v1/netlify", NetlifyRoute);
};

export default setupRoutes;
